packages:
  - apps/*
  - packages/*

allowBuilds:
  protobufjs: false
  simple-git-hooks: true

minimumReleaseAgeExclude:
  - mithril-markdown-wysiwyg@0.4.0
  - slimdown-js
  - mithril-materialized

onlyBuiltDependencies: []
